[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.20.6"

[functions]
  directory = "netlify/functions"

# Prevent secrets scanning from failing the build
[build.processing]
  skip_processing = true

[build.processing.html]
  pretty_urls = true

# Configure secrets scanning
[secrets]
  SECRETS_SCAN_OMIT_PATHS = ["dist/assets/*"]

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self' https://*.supabase.co https://*.stripe.com https://api.openai.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.supabase.co https://*.stripe.com https://cdn.jsdelivr.net https://unpkg.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: https://* blob:;
      font-src 'self' https://fonts.gstatic.com data:;
      connect-src 'self' https://*.supabase.co https://*.stripe.com https://api.openai.com https://*.netlify.app wss://*.supabase.co;
      frame-src https://*.stripe.com;
      worker-src 'self' blob:;
      manifest-src 'self'
    """
    object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      upgrade-insecure-requests;
      block-all-mixed-content
    """
