[build]
  command = "npm run build"
  publish = "dist"

[build.processing]
  skip_processing = false
  minify = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[secrets]
  SECRETS_SCAN_OMIT_PATHS = ["dist/assets/*"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    Content-Security-Policy = "default-src 'self' https://*.supabase.co https://*.stripe.com https://api.openai.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.supabase.co https://*.stripe.com https://cdn.jsdelivr.net https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://* blob:; font-src 'self' https://fonts.gstatic.com data:; connect-src 'self' https://*.supabase.co https://*.stripe.com https://api.openai.com https://*.netlify.app wss://*.supabase.co https://accounts.google.com https://*.googleusercontent.com https://oauth2.googleapis.com; frame-src https://*.stripe.com https://accounts.google.com https://*.googleusercontent.com; worker-src 'self' blob:; manifest-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; upgrade-insecure-requests; block-all-mixed-content"

[[context."deploy-preview".headers]]
  for = "/*"
  [context."deploy-preview".headers.values]
    Content-Security-Policy = "default-src 'self' https://*.supabase.co https://*.stripe.com https://api.openai.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.supabase.co https://*.stripe.com https://cdn.jsdelivr.net https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://* blob:; font-src 'self' https://fonts.gstatic.com data:; connect-src 'self' https://*.supabase.co https://*.stripe.com https://api.openai.com https://*.netlify.app wss://*.supabase.co https://accounts.google.com https://*.googleusercontent.com https://oauth2.googleapis.com; frame-src https://*.stripe.com https://accounts.google.com https://*.googleusercontent.com; worker-src 'self' blob:; manifest-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; upgrade-insecure-requests; block-all-mixed-content"